language: php
php:
  - "5.4"
  - "5.5"
services:
  - mongodb
env: LEMUR_ENV=travis
before_script:
  - cd app
  - echo "extension=mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install
  - mkdir -p -m 777 /var/cache/doctrine/odm/mongodb/Proxy
  - mkdir -p -m 777 /var/cache/doctrine/odm/mongodb/Hydrator
